sudo: required
language: node_js
node_js:
  - 10
env:
  global:
    - CXX=g++-4.8
    - CHROME_BIN=/usr/bin/google-chrome
    - DISPLAY=:99.0
addons:
  chrome: stable
install:
  - npm install
script:
  - sudo apt update
  - sudo apt install openjdk-8-jdk
  - 'java --version'
  - npm test
