sudo: required
language: node_js
node_js:
  - 10
#env:
#  global:
#    - CXX=g++-4.8
#    - CHROME_BIN=/usr/bin/google-chrome
#    - DISPLAY=:99.0
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # the starting the virtual X frame buffer: Xvfb process
  - sleep 3 #wait a while before xvfb to start
after_script:
  - "sh -e /etc/init.d/xvfb stop" #graceful shutdown
install:
  - npm install
script:
  - 'java --version'
  - pwd
  - whoami
  - npm test
