sudo: required
language: node_js
node_js:
  - 10
env:
  global:
    - CHROME_BIN=/usr/bin/google-chrome
    - DISPLAY=:99.0
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - oracle-java8-set-default
install:
  - npm install
script:
  - 'java --version'
  - pwd
  - whoami
  - npm test
