sudo: required
language: node_js
node_js:
  - 10
env:
  global:
    - CXX=g++-4.8
    - CHROME_BIN=/usr/bin/google-chrome
    - DISPLAY=:99.0
addons:
  chrome: stable
install:
  - npm install
script:
  - 'java --version'
  - pwd
  - whoami
  - chmod a+r /usr/lib/node_modules/decktape/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/*
  - chmod a+x /usr/lib/node_modules/decktape/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome
  - npm test
