sudo: required
language: node_js
node_js:
  - 10
env:
  global:
    - CXX=g++-4.8
    - CHROME_BIN=/usr/bin/google-chrome
    - DISPLAY=:99.0
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - oracle-java8-set-default
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 #wait a while before xvfb to start
install:
  - npm install
script:
  - 'java --version'
  - pwd
  - whoami
  - npm test
